CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Module" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_Module" PRIMARY KEY ("Id")
);

CREATE TABLE "OutboxMessage" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Content" text NOT NULL,
    "CreatedOnUtc" timestamp with time zone NOT NULL,
    "ProcessedOnUtc" timestamp with time zone,
    "Error" text,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("Id")
);

CREATE TABLE "Role" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Role" PRIMARY KEY ("Id")
);

CREATE TABLE "Tenant" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "ConnectionString" text,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Tenant" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" uuid NOT NULL,
    "Login" text NOT NULL,
    "Password" text NOT NULL,
    "FullName" text NOT NULL,
    "CellPhone" text,
    "Email" text,
    "SelectedStoreId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "Feature" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Description" text NOT NULL,
    "ModuleId" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    "Order" integer NOT NULL,
    CONSTRAINT "PK_Feature" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Feature_Module_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Module" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Owner" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Description" text NOT NULL,
    "Guest" boolean NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Owner" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Owner_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "UserRole" (
    "UserId" uuid NOT NULL,
    "RoleId" integer NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_UserRole" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRole_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_UserRole_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Store" (
    "Id" uuid NOT NULL,
    "Name" text NOT NULL,
    "Address" text,
    "Description" text,
    "Approved" boolean NOT NULL,
    "OwnerId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_Store" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Store_Owner_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Owner" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StoreFeature" (
    "StoreId" uuid NOT NULL,
    "FeatureId" integer NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StoreFeature" PRIMARY KEY ("StoreId", "FeatureId"),
    CONSTRAINT "FK_StoreFeature_Feature_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Feature" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoreFeature_Store_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Store" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StoreRoleFeature" (
    "StoreId" uuid NOT NULL,
    "RoleId" integer NOT NULL,
    "FeatureId" integer NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StoreRoleFeature" PRIMARY KEY ("StoreId", "RoleId", "FeatureId"),
    CONSTRAINT "FK_StoreRoleFeature_Feature_FeatureId" FOREIGN KEY ("FeatureId") REFERENCES "Feature" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoreRoleFeature_Role_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Role" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoreRoleFeature_Store_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Store" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StoreUser" (
    "UserId" uuid NOT NULL,
    "StoreId" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StoreUser" PRIMARY KEY ("UserId", "StoreId"),
    CONSTRAINT "FK_StoreUser_Store_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Store" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoreUser_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (1, TRUE, 'Administración', 0);
INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (2, TRUE, 'Ventas', 10);
INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (3, TRUE, 'Inventario', 20);
INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (4, TRUE, 'Sincronización', 30);
INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (5, TRUE, 'Estadísticas', 40);
INSERT INTO "Module" ("Id", "IsActive", "Name", "Order")
VALUES (6, TRUE, 'Gestión', 50);

INSERT INTO "Role" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
VALUES (1, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.860103+00:00', 'Este Role permitirá acceder a todas las funcionalidades en todos los tenants.', TRUE, 'Super Administrador', NULL, NULL);
INSERT INTO "Role" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
VALUES (2, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.860109+00:00', 'Este Role permitirá acceder a todas las funcionalidades de la tienda.', TRUE, 'Administrador de tienda', NULL, NULL);
INSERT INTO "Role" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
VALUES (3, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.860113+00:00', 'Este Role permitirá acceder a las funcionalidades para un usuario de la tienda.', TRUE, 'Usuario de tienda', NULL, NULL);

INSERT INTO "Tenant" ("Id", "ConnectionString", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
VALUES ('b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', '', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.859319+00:00', 'Default Tenant to create Default Store for Super Admin User', TRUE, 'Default Tenant', NULL, NULL);

INSERT INTO "User" ("Id", "CellPhone", "CreatedBy", "CreatedDate", "Email", "FullName", "IsActive", "Login", "Password", "SelectedStoreId", "TenantId", "UpdatedBy", "UpdatedDate")
VALUES ('38b96d85-bf75-41ca-bfd7-796e7fe0ebc8', '52432968', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.859509+00:00', 'lrscott83@gmail.com', 'Lizardo Romero', TRUE, 'admin', 'XwHSL3RwmY9AkQLdRIeWr/H1xHm7ulj/la+EYwkLgrA=', '00000000-0000-0000-0000-000000000000', 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', NULL, NULL);

INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (10, 'Funcionalidad para gestionar los tenants', TRUE, 1, 'Tenants', 0);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (11, 'Funcionalidad para gestionar los propietarios', TRUE, 1, 'Propietarios', 10);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (20, 'Funcionalidad para gestionar los productos', TRUE, 2, 'Productos', 20);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (21, 'Funcionalidad para gestionar la venta', TRUE, 2, 'Venta', 30);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (22, 'Funcionalidad para gestionar las ventas del día', TRUE, 2, 'Ventas del día', 40);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (23, 'Funcionalidad para revisar el cuadre de las ventas del día', TRUE, 2, 'Cuadre del día', 50);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (30, 'Funcionalidad para listar la disponibilidad del inventario', TRUE, 3, 'Disponible', 60);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (31, 'Funcionalidad para gestionar las entradas al inventario', TRUE, 3, 'Entradas', 70);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (32, 'Funcionalidad para revisar el cuadre de las entradas del día al inventario', TRUE, 3, 'Cuadre del día', 80);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (40, 'Funcionalidad para enviar los datos', TRUE, 4, 'Enviar', 90);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (41, 'Funcionalidad para descargar los datos', TRUE, 4, 'Descargar', 100);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (42, 'Funcionalidad para recibir los datos', TRUE, 4, 'Recibir', 110);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (50, 'Funcionalidad para el cuadro de mando', TRUE, 5, 'Dashboard', 120);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (60, 'Funcionalidad para gestionar el perfil del usuario autenticado', TRUE, 6, 'Perfil', 130);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (61, 'Funcionalidad para gestionar los usuarios', TRUE, 6, 'Usuarios', 140);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (62, 'Funcionalidad para gestionar los roles', TRUE, 6, 'Roles', 150);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (63, 'Funcionalidad para gestionar las tiendas', TRUE, 6, 'Tiendas', 160);
INSERT INTO "Feature" ("Id", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (64, 'Funcionalidad para gestionar las configuraciones', TRUE, 6, 'Configuraciones', 170);

INSERT INTO "Owner" ("Id", "CreatedBy", "CreatedDate", "Description", "Guest", "IsActive", "TenantId", "UpdatedBy", "UpdatedDate", "UserId")
VALUES ('b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.861438+00:00', 'Admin Owner', TRUE, TRUE, 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', NULL, NULL, '38b96d85-bf75-41ca-bfd7-796e7fe0ebc8');

INSERT INTO "UserRole" ("RoleId", "UserId", "CreatedBy", "CreatedDate", "IsActive", "TenantId", "UpdatedBy", "UpdatedDate")
VALUES (1, '38b96d85-bf75-41ca-bfd7-796e7fe0ebc8', '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '-infinity', TRUE, 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', NULL, NULL);

INSERT INTO "Store" ("Id", "Address", "Approved", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "OwnerId", "TenantId", "UpdatedBy", "UpdatedDate")
VALUES ('0ed24a91-6748-4f04-8902-7981a0ca79e0', NULL, FALSE, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2024-08-26T13:28:42.860659+00:00', NULL, TRUE, 'Default Store', 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8', NULL, NULL);

CREATE INDEX "IX_Feature_ModuleId" ON "Feature" ("ModuleId");

CREATE INDEX "IX_Owner_TenantId" ON "Owner" ("TenantId");

CREATE UNIQUE INDEX "IX_Owner_UserId" ON "Owner" ("UserId");

CREATE INDEX "IX_Store_OwnerId" ON "Store" ("OwnerId");

CREATE INDEX "IX_Store_TenantId" ON "Store" ("TenantId");

CREATE INDEX "IX_StoreFeature_FeatureId" ON "StoreFeature" ("FeatureId");

CREATE INDEX "IX_StoreFeature_TenantId" ON "StoreFeature" ("TenantId");

CREATE INDEX "IX_StoreRoleFeature_FeatureId" ON "StoreRoleFeature" ("FeatureId");

CREATE INDEX "IX_StoreRoleFeature_RoleId" ON "StoreRoleFeature" ("RoleId");

CREATE INDEX "IX_StoreRoleFeature_TenantId" ON "StoreRoleFeature" ("TenantId");

CREATE INDEX "IX_StoreUser_StoreId" ON "StoreUser" ("StoreId");

CREATE INDEX "IX_StoreUser_TenantId" ON "StoreUser" ("TenantId");

CREATE UNIQUE INDEX "IX_StoreUser_UserId" ON "StoreUser" ("UserId");

CREATE UNIQUE INDEX "IX_Tenant_Name" ON "Tenant" ("Name");

CREATE UNIQUE INDEX "IX_User_Login" ON "User" ("Login");

CREATE INDEX "IX_User_TenantId" ON "User" ("TenantId");

CREATE INDEX "IX_UserRole_RoleId" ON "UserRole" ("RoleId");

CREATE INDEX "IX_UserRole_TenantId" ON "UserRole" ("TenantId");

SELECT setval(
    pg_get_serial_sequence('"Module"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Module") + 1,
        nextval(pg_get_serial_sequence('"Module"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Role"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Role") + 1,
        nextval(pg_get_serial_sequence('"Role"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Feature"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Feature") + 1,
        nextval(pg_get_serial_sequence('"Feature"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240826132843_InitialCreate', '8.0.3');

COMMIT;

START TRANSACTION;

DROP TABLE "StoreFeature";

DROP INDEX "IX_Store_TenantId";

DROP INDEX "IX_Owner_TenantId";

DELETE FROM "Feature"
WHERE "Id" = 62;

DELETE FROM "Store"
WHERE "Id" = '0ed24a91-6748-4f04-8902-7981a0ca79e0';

DELETE FROM "Owner"
WHERE "Id" = 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8';

ALTER TABLE "Module" ADD "AvailableToStore" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Module" ADD "DiscountPrice" real NOT NULL DEFAULT 0;

ALTER TABLE "Module" ADD "PercentDiscountPrice" real NOT NULL DEFAULT 0;

ALTER TABLE "Module" ADD "Price" real NOT NULL DEFAULT 0;

ALTER TABLE "Module" ADD "PriceIncluded" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Feature" ADD "AvailableToStore" boolean NOT NULL DEFAULT FALSE;

CREATE TABLE "StoreModule" (
    "StoreId" uuid NOT NULL,
    "ModuleId" integer NOT NULL,
    "ModulePriceIncluded" boolean NOT NULL,
    "Price" real NOT NULL,
    "ModulePrice" real NOT NULL,
    "ModuleDiscountPrice" real NOT NULL,
    "ModulePercentDiscountPrice" real NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StoreModule" PRIMARY KEY ("StoreId", "ModuleId"),
    CONSTRAINT "FK_StoreModule_Module_ModuleId" FOREIGN KEY ("ModuleId") REFERENCES "Module" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StoreModule_Store_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Store" ("Id") ON DELETE RESTRICT
);

UPDATE "Feature" SET "AvailableToStore" = FALSE
WHERE "Id" = 10;

UPDATE "Feature" SET "AvailableToStore" = FALSE
WHERE "Id" = 11;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 20;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 21;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 22;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 23;

UPDATE "Feature" SET "AvailableToStore" = TRUE, "IsActive" = FALSE
WHERE "Id" = 30;

UPDATE "Feature" SET "AvailableToStore" = TRUE, "IsActive" = FALSE
WHERE "Id" = 31;

UPDATE "Feature" SET "AvailableToStore" = TRUE, "IsActive" = FALSE
WHERE "Id" = 32;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 40;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 41;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 42;

UPDATE "Feature" SET "AvailableToStore" = TRUE, "IsActive" = FALSE
WHERE "Id" = 50;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 60;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 61;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 63;

UPDATE "Feature" SET "AvailableToStore" = TRUE
WHERE "Id" = 64;

INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (12, FALSE, 'Funcionalidad para gestionar los roles', TRUE, 1, 'Roles', 20);

UPDATE "Module" SET "AvailableToStore" = FALSE, "DiscountPrice" = 0, "PercentDiscountPrice" = 0, "Price" = 3.4028235E+38, "PriceIncluded" = FALSE
WHERE "Id" = 1;

UPDATE "Module" SET "AvailableToStore" = TRUE, "DiscountPrice" = 0, "PercentDiscountPrice" = 0, "Price" = 0, "PriceIncluded" = TRUE
WHERE "Id" = 2;

UPDATE "Module" SET "AvailableToStore" = TRUE, "DiscountPrice" = 0, "IsActive" = FALSE, "PercentDiscountPrice" = 0, "Price" = 500, "PriceIncluded" = FALSE
WHERE "Id" = 3;

UPDATE "Module" SET "AvailableToStore" = TRUE, "DiscountPrice" = 0, "PercentDiscountPrice" = 100, "Price" = 500, "PriceIncluded" = TRUE
WHERE "Id" = 4;

UPDATE "Module" SET "AvailableToStore" = TRUE, "DiscountPrice" = 0, "IsActive" = FALSE, "PercentDiscountPrice" = 0, "Price" = 500, "PriceIncluded" = FALSE
WHERE "Id" = 5;

UPDATE "Module" SET "AvailableToStore" = TRUE, "DiscountPrice" = 0, "PercentDiscountPrice" = 0, "Price" = 0, "PriceIncluded" = TRUE
WHERE "Id" = 6;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2024-09-10T19:49:34.453806+00:00'
WHERE "Id" = 1;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2024-09-10T19:49:34.453817+00:00'
WHERE "Id" = 2;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2024-09-10T19:49:34.453821+00:00'
WHERE "Id" = 3;

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMPTZ '2024-09-10T19:49:34.453045+00:00'
WHERE "Id" = 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8';

UPDATE "User" SET "CreatedDate" = TIMESTAMPTZ '2024-09-10T19:49:34.453225+00:00'
WHERE "Id" = '38b96d85-bf75-41ca-bfd7-796e7fe0ebc8';

CREATE INDEX "IX_StoreModule_ModuleId" ON "StoreModule" ("ModuleId");

CREATE INDEX "IX_StoreModule_TenantId" ON "StoreModule" ("TenantId");

SELECT setval(
    pg_get_serial_sequence('"Feature"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Feature") + 1,
        nextval(pg_get_serial_sequence('"Feature"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20240910194934_Create-Store-Module-Price', '8.0.3');

COMMIT;

START TRANSACTION;

ALTER TABLE "Store" ADD "PaymentStartDate" date NOT NULL DEFAULT DATE '-infinity';

CREATE TABLE "ReSeller" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Approved" boolean NOT NULL,
    "DiscountPrice" real NOT NULL,
    "PercentDiscountPrice" real NOT NULL,
    "Description" text NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ReSeller" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReSeller_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StorePaymentStatus" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    CONSTRAINT "PK_StorePaymentStatus" PRIMARY KEY ("Id")
);

CREATE TABLE "SystemConfiguration" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Value" text NOT NULL,
    CONSTRAINT "PK_SystemConfiguration" PRIMARY KEY ("Id")
);

CREATE TABLE "ReSellerOwner" (
    "ReSellerId" uuid NOT NULL,
    "OwnerId" uuid NOT NULL,
    "DiscountPrice" real NOT NULL,
    "PercentDiscountPrice" real NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_ReSellerOwner" PRIMARY KEY ("ReSellerId", "OwnerId"),
    CONSTRAINT "FK_ReSellerOwner_Owner_OwnerId" FOREIGN KEY ("OwnerId") REFERENCES "Owner" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_ReSellerOwner_ReSeller_ReSellerId" FOREIGN KEY ("ReSellerId") REFERENCES "ReSeller" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "StorePayment" (
    "Id" uuid NOT NULL,
    "StoreId" uuid NOT NULL,
    "StorePaymentStatusId" integer NOT NULL,
    "PaidDate" timestamp with time zone,
    "NotificationDate" timestamp with time zone,
    "PaymentBeforeDate" timestamp with time zone NOT NULL,
    "Price" real NOT NULL,
    "Year" integer NOT NULL,
    "Month" integer NOT NULL,
    "TenantId" uuid NOT NULL,
    "IsActive" boolean NOT NULL,
    "CreatedDate" timestamp with time zone NOT NULL,
    "CreatedBy" uuid NOT NULL,
    "UpdatedDate" timestamp with time zone,
    "UpdatedBy" uuid,
    CONSTRAINT "PK_StorePayment" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_StorePayment_StorePaymentStatus_StorePaymentStatusId" FOREIGN KEY ("StorePaymentStatusId") REFERENCES "StorePaymentStatus" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_StorePayment_Store_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Store" ("Id") ON DELETE RESTRICT
);

UPDATE "Feature" SET "Order" = 30
WHERE "Id" = 12;

INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (13, FALSE, 'Funcionalidad para gestionar los gestores', TRUE, 1, 'Gestores', 20);

UPDATE "Module" SET "Price" = 500
WHERE "Id" = 2;

UPDATE "Module" SET "PriceIncluded" = FALSE
WHERE "Id" = 4;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-01-16T14:55:20.456479+00:00'
WHERE "Id" = 1;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-01-16T14:55:20.456489+00:00'
WHERE "Id" = 2;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-01-16T14:55:20.456493+00:00'
WHERE "Id" = 3;

INSERT INTO "Role" ("Id", "CreatedBy", "CreatedDate", "Description", "IsActive", "Name", "UpdatedBy", "UpdatedDate")
VALUES (4, '00000000-0000-0000-0000-000000000000', TIMESTAMPTZ '2025-01-16T14:55:20.456497+00:00', 'Este Role permitirá acceder a las funcionalidades para un usuario comercializador del servicio.', TRUE, 'Comercializador del servicio', NULL, NULL);

INSERT INTO "StorePaymentStatus" ("Id", "Name")
VALUES (1, 'Created');
INSERT INTO "StorePaymentStatus" ("Id", "Name")
VALUES (2, 'Notified');
INSERT INTO "StorePaymentStatus" ("Id", "Name")
VALUES (3, 'Invoiced');
INSERT INTO "StorePaymentStatus" ("Id", "Name")
VALUES (4, 'Approved');
INSERT INTO "StorePaymentStatus" ("Id", "Name")
VALUES (5, 'Paid');

INSERT INTO "SystemConfiguration" ("Id", "Name", "Value")
VALUES (1, 'TestingPeriodInMonths', '1');
INSERT INTO "SystemConfiguration" ("Id", "Name", "Value")
VALUES (2, 'ReSellerPercentDiscountPrice', '25');

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMPTZ '2025-01-16T14:55:20.455624+00:00'
WHERE "Id" = 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8';

UPDATE "User" SET "CreatedDate" = TIMESTAMPTZ '2025-01-16T14:55:20.455838+00:00'
WHERE "Id" = '38b96d85-bf75-41ca-bfd7-796e7fe0ebc8';

CREATE INDEX "IX_StoreModule_StoreId" ON "StoreModule" ("StoreId");

CREATE INDEX "IX_Owner_TenantId" ON "Owner" ("TenantId");

CREATE INDEX "IX_ReSeller_TenantId" ON "ReSeller" ("TenantId");

CREATE UNIQUE INDEX "IX_ReSeller_UserId" ON "ReSeller" ("UserId");

CREATE UNIQUE INDEX "IX_ReSellerOwner_OwnerId" ON "ReSellerOwner" ("OwnerId");

CREATE INDEX "IX_ReSellerOwner_ReSellerId" ON "ReSellerOwner" ("ReSellerId");

CREATE INDEX "IX_ReSellerOwner_TenantId" ON "ReSellerOwner" ("TenantId");

CREATE INDEX "IX_StorePayment_StoreId" ON "StorePayment" ("StoreId");

CREATE INDEX "IX_StorePayment_StorePaymentStatusId" ON "StorePayment" ("StorePaymentStatusId");

CREATE INDEX "IX_StorePayment_TenantId" ON "StorePayment" ("TenantId");

CREATE UNIQUE INDEX "IX_SystemConfiguration_Name" ON "SystemConfiguration" ("Name");

SELECT setval(
    pg_get_serial_sequence('"Feature"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Feature") + 1,
        nextval(pg_get_serial_sequence('"Feature"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Role"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Role") + 1,
        nextval(pg_get_serial_sequence('"Role"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"StorePaymentStatus"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "StorePaymentStatus") + 1,
        nextval(pg_get_serial_sequence('"StorePaymentStatus"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"SystemConfiguration"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "SystemConfiguration") + 1,
        nextval(pg_get_serial_sequence('"SystemConfiguration"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250116145520_Create-ReSeller-StorePayment-Tables', '8.0.3');

COMMIT;

START TRANSACTION;

DELETE FROM "Feature"
WHERE "Id" = 61;

DELETE FROM "Feature"
WHERE "Id" = 63;

DELETE FROM "Feature"
WHERE "Id" = 64;

UPDATE "Feature" SET "IsActive" = TRUE
WHERE "Id" = 30;

UPDATE "Feature" SET "IsActive" = TRUE
WHERE "Id" = 31;

UPDATE "Feature" SET "IsActive" = TRUE
WHERE "Id" = 32;

UPDATE "Feature" SET "Description" = 'Funcionalidad para los reportes del día', "Name" = 'Reportes del día'
WHERE "Id" = 50;

UPDATE "Feature" SET "Description" = 'Funcionalidad para el cuadro de mando', "IsActive" = FALSE, "Name" = 'Dashboard'
WHERE "Id" = 60;

UPDATE "Module" SET "Price" = 1000
WHERE "Id" = 2;

UPDATE "Module" SET "IsActive" = TRUE, "Price" = 1000
WHERE "Id" = 3;

UPDATE "Module" SET "PercentDiscountPrice" = 0, "Price" = 1000
WHERE "Id" = 4;

UPDATE "Module" SET "IsActive" = TRUE, "Name" = 'Reportes', "Price" = 1000
WHERE "Id" = 5;

UPDATE "Module" SET "IsActive" = FALSE, "Name" = 'Estadísticas', "Price" = 2000, "PriceIncluded" = FALSE
WHERE "Id" = 6;

INSERT INTO "Module" ("Id", "AvailableToStore", "DiscountPrice", "IsActive", "Name", "Order", "PercentDiscountPrice", "Price", "PriceIncluded")
VALUES (7, TRUE, 0, TRUE, 'Gestión', 60, 0, 0, TRUE);

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.487441+00:00'
WHERE "Id" = 1;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.487447+00:00'
WHERE "Id" = 2;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.487452+00:00'
WHERE "Id" = 3;

UPDATE "Role" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.487456+00:00'
WHERE "Id" = 4;

UPDATE "Tenant" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.48655+00:00'
WHERE "Id" = 'b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8';

UPDATE "User" SET "CreatedDate" = TIMESTAMPTZ '2025-04-13T18:50:15.48677+00:00'
WHERE "Id" = '38b96d85-bf75-41ca-bfd7-796e7fe0ebc8';

INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (70, TRUE, 'Funcionalidad para gestionar el perfil del usuario autenticado', TRUE, 7, 'Perfil', 140);
INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (72, TRUE, 'Funcionalidad para gestionar los usuarios', TRUE, 7, 'Usuarios', 150);
INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (73, TRUE, 'Funcionalidad para gestionar las tiendas', TRUE, 7, 'Tiendas', 160);
INSERT INTO "Feature" ("Id", "AvailableToStore", "Description", "IsActive", "ModuleId", "Name", "Order")
VALUES (74, TRUE, 'Funcionalidad para gestionar las configuraciones', TRUE, 7, 'Configuraciones', 170);

SELECT setval(
    pg_get_serial_sequence('"Module"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Module") + 1,
        nextval(pg_get_serial_sequence('"Module"', 'Id'))),
    false);
SELECT setval(
    pg_get_serial_sequence('"Feature"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "Feature") + 1,
        nextval(pg_get_serial_sequence('"Feature"', 'Id'))),
    false);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20250413185015_Add_Reports_Module', '8.0.3');

COMMIT;

