-- =====================================================
-- 12: Add StorePlans table (Gratis/Pago/Superior/VIP)
--     + Store.StorePlanId column with DEFAULT 2 (Pago) + FK Restrict
-- EF migration: 20260908194349_Add-StorePlans
-- Date: 2026-09-08
-- Parity: CREATE TABLE + seed (4 plans) + column + backfill mirror the EF
--         migration exactly. Existing stores are credited with Pago (2),
--         the same value the column default writes.
-- =====================================================

BEGIN;

-- --- Table: StorePlan (+ seed Gratis=1, Pago=2, Superior=3, VIP=4) ---
CREATE TABLE IF NOT EXISTS "StorePlan" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Name" text NOT NULL,
    "Order" integer NOT NULL,
    "IsActive" boolean NOT NULL,
    CONSTRAINT "PK_StorePlan" PRIMARY KEY ("Id")
);

INSERT INTO "StorePlan" ("Id", "IsActive", "Name", "Order")
VALUES (1, TRUE, 'Gratis', 1),
       (2, TRUE, 'Pago', 2),
       (3, TRUE, 'Superior', 3),
       (4, TRUE, 'VIP', 4)
ON CONFLICT ("Id") DO NOTHING;

-- --- Store.StorePlanId (NOT NULL, DEFAULT 2 = Pago) ---
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "StorePlanId" integer NOT NULL DEFAULT 2;

-- Backfill existing stores: Pago (2) — same intent as the EF migration's
-- explicit UPDATE (the column default already wrote 2 for existing rows;
-- kept explicit so the migration and this script stay in sync).
UPDATE "Store" SET "StorePlanId" = 2;

CREATE INDEX IF NOT EXISTS "IX_Store_StorePlanId" ON "Store" ("StorePlanId");

ALTER TABLE "Store" ADD CONSTRAINT "FK_Store_StorePlan_StorePlanId"
    FOREIGN KEY ("StorePlanId") REFERENCES "StorePlan" ("Id") ON DELETE RESTRICT;

-- --- Sequence fix-up: explicit PK inserts do not advance the identity ---
SELECT setval(
    pg_get_serial_sequence('"StorePlan"', 'Id'),
    GREATEST(
        (SELECT MAX("Id") FROM "StorePlan") + 1,
        nextval(pg_get_serial_sequence('"StorePlan"', 'Id'))),
    false);

-- --- Register the EF migration so `dotnet ef database update` stays in sync ---
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260908194349_Add-StorePlans', '8.0.3')
ON CONFLICT ("MigrationId") DO NOTHING;

COMMIT;

-- --- Verification ---
SELECT "Id", "Name", "Order", "IsActive" FROM "StorePlan" ORDER BY "Id";

SELECT COUNT(*) AS total_stores,
       COUNT(*) FILTER (WHERE "StorePlanId" = 2) AS stores_with_pago_plan
FROM "Store";

SELECT "Id", "StorePlanId" FROM "Store" ORDER BY "Id" LIMIT 5;

-- =====================================================
-- ROLLBACK (inverse operations, run manually if needed):
--
-- BEGIN;
-- ALTER TABLE "Store" DROP CONSTRAINT "FK_Store_StorePlan_StorePlanId";
-- ALTER TABLE "Store" DROP COLUMN "StorePlanId";
-- DROP TABLE "StorePlan";
-- DELETE FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260908194349_Add-StorePlans';
-- COMMIT;
-- =====================================================