// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240826132843_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Feature");

                    b.HasData(
                        new
                        {
                            Id = 10,
                            Description = "Funcionalidad para gestionar los tenants",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Tenants",
                            Order = 0
                        },
                        new
                        {
                            Id = 11,
                            Description = "Funcionalidad para gestionar los propietarios",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Propietarios",
                            Order = 10
                        },
                        new
                        {
                            Id = 20,
                            Description = "Funcionalidad para gestionar los productos",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Productos",
                            Order = 20
                        },
                        new
                        {
                            Id = 21,
                            Description = "Funcionalidad para gestionar la venta",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Venta",
                            Order = 30
                        },
                        new
                        {
                            Id = 22,
                            Description = "Funcionalidad para gestionar las ventas del día",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Ventas del día",
                            Order = 40
                        },
                        new
                        {
                            Id = 23,
                            Description = "Funcionalidad para revisar el cuadre de las ventas del día",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Cuadre del día",
                            Order = 50
                        },
                        new
                        {
                            Id = 30,
                            Description = "Funcionalidad para listar la disponibilidad del inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Disponible",
                            Order = 60
                        },
                        new
                        {
                            Id = 31,
                            Description = "Funcionalidad para gestionar las entradas al inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Entradas",
                            Order = 70
                        },
                        new
                        {
                            Id = 32,
                            Description = "Funcionalidad para revisar el cuadre de las entradas del día al inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Cuadre del día",
                            Order = 80
                        },
                        new
                        {
                            Id = 40,
                            Description = "Funcionalidad para enviar los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Enviar",
                            Order = 90
                        },
                        new
                        {
                            Id = 41,
                            Description = "Funcionalidad para descargar los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Descargar",
                            Order = 100
                        },
                        new
                        {
                            Id = 42,
                            Description = "Funcionalidad para recibir los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Recibir",
                            Order = 110
                        },
                        new
                        {
                            Id = 50,
                            Description = "Funcionalidad para el cuadro de mando",
                            IsActive = true,
                            ModuleId = 5,
                            Name = "Dashboard",
                            Order = 120
                        },
                        new
                        {
                            Id = 60,
                            Description = "Funcionalidad para gestionar el perfil del usuario autenticado",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "Perfil",
                            Order = 130
                        },
                        new
                        {
                            Id = 61,
                            Description = "Funcionalidad para gestionar los usuarios",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "Usuarios",
                            Order = 140
                        },
                        new
                        {
                            Id = 62,
                            Description = "Funcionalidad para gestionar los roles",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "Roles",
                            Order = 150
                        },
                        new
                        {
                            Id = 63,
                            Description = "Funcionalidad para gestionar las tiendas",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "Tiendas",
                            Order = 160
                        },
                        new
                        {
                            Id = 64,
                            Description = "Funcionalidad para gestionar las configuraciones",
                            IsActive = true,
                            ModuleId = 6,
                            Name = "Configuraciones",
                            Order = 170
                        });
                });

            modelBuilder.Entity("Domain.Entities.Modules.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Module");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Administración",
                            Order = 0
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Ventas",
                            Order = 10
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Inventario",
                            Order = 20
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Sincronización",
                            Order = 30
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Estadísticas",
                            Order = 40
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Gestión",
                            Order = 50
                        });
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Guest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Owner");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8"),
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 861, DateTimeKind.Unspecified).AddTicks(4382), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Admin Owner",
                            Guest = true,
                            IsActive = true,
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8"),
                            UserId = new Guid("38b96d85-bf75-41ca-bfd7-796e7fe0ebc8")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 860, DateTimeKind.Unspecified).AddTicks(1039), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a todas las funcionalidades en todos los tenants.",
                            IsActive = true,
                            Name = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 860, DateTimeKind.Unspecified).AddTicks(1094), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a todas las funcionalidades de la tienda.",
                            IsActive = true,
                            Name = "Administrador de tienda"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 860, DateTimeKind.Unspecified).AddTicks(1137), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a las funcionalidades para un usuario de la tienda.",
                            IsActive = true,
                            Name = "Usuario de tienda"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StoreFeatures.StoreFeature", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("TenantId");

                    b.ToTable("StoreFeature");
                });

            modelBuilder.Entity("Domain.Entities.StoreRoleFeatures.StoreRoleFeature", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId", "RoleId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("StoreRoleFeature");
                });

            modelBuilder.Entity("Domain.Entities.StoreUsers.StoreUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StoreUser");
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TenantId");

                    b.ToTable("Store");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ed24a91-6748-4f04-8902-7981a0ca79e0"),
                            Approved = false,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 860, DateTimeKind.Unspecified).AddTicks(6599), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            Name = "Default Store",
                            OwnerId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8"),
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenant");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8"),
                            ConnectionString = "",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 859, DateTimeKind.Unspecified).AddTicks(3196), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default Tenant to create Default Store for Super Admin User",
                            IsActive = true,
                            Name = "Default Tenant"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserRoles.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserRole");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("38b96d85-bf75-41ca-bfd7-796e7fe0ebc8"),
                            RoleId = 1,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SelectedStoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("38b96d85-bf75-41ca-bfd7-796e7fe0ebc8"),
                            CellPhone = "52432968",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2024, 8, 26, 13, 28, 42, 859, DateTimeKind.Unspecified).AddTicks(5097), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "lrscott83@gmail.com",
                            FullName = "Lizardo Romero",
                            IsActive = true,
                            Login = "admin",
                            Password = "XwHSL3RwmY9AkQLdRIeWr/H1xHm7ulj/la+EYwkLgrA=",
                            SelectedStoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8")
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.HasOne("Domain.Entities.Modules.Module", "Module")
                        .WithMany("Features")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("Owner")
                        .HasForeignKey("Domain.Entities.Owners.Owner", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.StoreFeatures.StoreFeature", b =>
                {
                    b.HasOne("Domain.Entities.Features.Feature", "Feature")
                        .WithMany("StoreFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreFeatures")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.StoreRoleFeatures.StoreRoleFeature", b =>
                {
                    b.HasOne("Domain.Entities.Features.Feature", "Feature")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.StoreUsers.StoreUser", b =>
                {
                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreUsers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("StoreUser")
                        .HasForeignKey("Domain.Entities.StoreUsers.StoreUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.HasOne("Domain.Entities.Owners.Owner", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.UserRoles.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.Navigation("StoreFeatures");

                    b.Navigation("StoreRoleFeatures");
                });

            modelBuilder.Entity("Domain.Entities.Modules.Module", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Navigation("StoreRoleFeatures");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.Navigation("StoreFeatures");

                    b.Navigation("StoreRoleFeatures");

                    b.Navigation("StoreUsers");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Owner");

                    b.Navigation("StoreUser");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
