// <auto-generated />
using System;
using Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvailableToStore")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId");

                    b.ToTable("Feature", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 10,
                            AvailableToStore = false,
                            Description = "Funcionalidad para gestionar los tenants",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Tenants",
                            Order = 0
                        },
                        new
                        {
                            Id = 11,
                            AvailableToStore = false,
                            Description = "Funcionalidad para gestionar los propietarios",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Propietarios",
                            Order = 10
                        },
                        new
                        {
                            Id = 13,
                            AvailableToStore = false,
                            Description = "Funcionalidad para gestionar los gestores",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Gestores",
                            Order = 20
                        },
                        new
                        {
                            Id = 12,
                            AvailableToStore = false,
                            Description = "Funcionalidad para gestionar los roles",
                            IsActive = true,
                            ModuleId = 1,
                            Name = "Roles",
                            Order = 30
                        },
                        new
                        {
                            Id = 20,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar los productos",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Productos",
                            Order = 20
                        },
                        new
                        {
                            Id = 21,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar la venta",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Venta",
                            Order = 30
                        },
                        new
                        {
                            Id = 22,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar las ventas del día",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Ventas del día",
                            Order = 40
                        },
                        new
                        {
                            Id = 23,
                            AvailableToStore = true,
                            Description = "Funcionalidad para revisar el cuadre de las ventas del día",
                            IsActive = true,
                            ModuleId = 2,
                            Name = "Cuadre del día",
                            Order = 50
                        },
                        new
                        {
                            Id = 30,
                            AvailableToStore = true,
                            Description = "Funcionalidad para listar la disponibilidad del inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Disponible",
                            Order = 60
                        },
                        new
                        {
                            Id = 31,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar las entradas al inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Entradas",
                            Order = 70
                        },
                        new
                        {
                            Id = 32,
                            AvailableToStore = true,
                            Description = "Funcionalidad para revisar el cuadre de las entradas del día al inventario",
                            IsActive = true,
                            ModuleId = 3,
                            Name = "Cuadre del día",
                            Order = 80
                        },
                        new
                        {
                            Id = 40,
                            AvailableToStore = true,
                            Description = "Funcionalidad para enviar los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Enviar",
                            Order = 90
                        },
                        new
                        {
                            Id = 41,
                            AvailableToStore = true,
                            Description = "Funcionalidad para descargar los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Descargar",
                            Order = 100
                        },
                        new
                        {
                            Id = 42,
                            AvailableToStore = true,
                            Description = "Funcionalidad para recibir los datos",
                            IsActive = true,
                            ModuleId = 4,
                            Name = "Recibir",
                            Order = 110
                        },
                        new
                        {
                            Id = 50,
                            AvailableToStore = true,
                            Description = "Funcionalidad para los reportes del día",
                            IsActive = false,
                            ModuleId = 5,
                            Name = "Reportes del día",
                            Order = 120
                        },
                        new
                        {
                            Id = 60,
                            AvailableToStore = true,
                            Description = "Funcionalidad para el cuadro de mando",
                            IsActive = false,
                            ModuleId = 6,
                            Name = "Dashboard",
                            Order = 130
                        },
                        new
                        {
                            Id = 70,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar el perfil del usuario autenticado",
                            IsActive = true,
                            ModuleId = 7,
                            Name = "Perfil",
                            Order = 140
                        },
                        new
                        {
                            Id = 72,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar los usuarios",
                            IsActive = true,
                            ModuleId = 7,
                            Name = "Usuarios",
                            Order = 150
                        },
                        new
                        {
                            Id = 73,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar las tiendas",
                            IsActive = true,
                            ModuleId = 7,
                            Name = "Tiendas",
                            Order = 160
                        },
                        new
                        {
                            Id = 74,
                            AvailableToStore = true,
                            Description = "Funcionalidad para gestionar las configuraciones",
                            IsActive = true,
                            ModuleId = 7,
                            Name = "Configuraciones",
                            Order = 170
                        });
                });

            modelBuilder.Entity("Domain.Entities.Modules.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AvailableToStore")
                        .HasColumnType("boolean");

                    b.Property<float>("DiscountPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<float>("PercentDiscountPrice")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("PriceIncluded")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Module", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableToStore = false,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Administración",
                            Order = 0,
                            PercentDiscountPrice = 0f,
                            Price = 3.4028235E+38f,
                            PriceIncluded = false
                        },
                        new
                        {
                            Id = 2,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Ventas",
                            Order = 10,
                            PercentDiscountPrice = 0f,
                            Price = 1000f,
                            PriceIncluded = true
                        },
                        new
                        {
                            Id = 3,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Inventario",
                            Order = 20,
                            PercentDiscountPrice = 0f,
                            Price = 1000f,
                            PriceIncluded = false
                        },
                        new
                        {
                            Id = 4,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Sincronización",
                            Order = 30,
                            PercentDiscountPrice = 0f,
                            Price = 1000f,
                            PriceIncluded = false
                        },
                        new
                        {
                            Id = 5,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Reportes",
                            Order = 40,
                            PercentDiscountPrice = 0f,
                            Price = 1000f,
                            PriceIncluded = false
                        },
                        new
                        {
                            Id = 6,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = false,
                            Name = "Estadísticas",
                            Order = 50,
                            PercentDiscountPrice = 0f,
                            Price = 2000f,
                            PriceIncluded = false
                        },
                        new
                        {
                            Id = 7,
                            AvailableToStore = true,
                            DiscountPrice = 0f,
                            IsActive = true,
                            Name = "Gestión",
                            Order = 60,
                            PercentDiscountPrice = 0f,
                            Price = 0f,
                            PriceIncluded = true
                        });
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Guest")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Owner", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReSellerOwners.ReSellerOwner", b =>
                {
                    b.Property<Guid>("ReSellerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("DiscountPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("PercentDiscountPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ReSellerId", "OwnerId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.HasIndex("ReSellerId");

                    b.HasIndex("TenantId");

                    b.ToTable("ReSellerOwner", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ReSellers.ReSeller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("DiscountPrice")
                        .HasColumnType("real");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("PercentDiscountPrice")
                        .HasColumnType("real");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ReSeller", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Role", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 487, DateTimeKind.Unspecified).AddTicks(4417), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a todas las funcionalidades en todos los tenants.",
                            IsActive = true,
                            Name = "Super Administrador"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 487, DateTimeKind.Unspecified).AddTicks(4476), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a todas las funcionalidades de la tienda.",
                            IsActive = true,
                            Name = "Administrador de tienda"
                        },
                        new
                        {
                            Id = 3,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 487, DateTimeKind.Unspecified).AddTicks(4521), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a las funcionalidades para un usuario de la tienda.",
                            IsActive = true,
                            Name = "Usuario de tienda"
                        },
                        new
                        {
                            Id = 4,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 487, DateTimeKind.Unspecified).AddTicks(4562), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Este Role permitirá acceder a las funcionalidades para un usuario comercializador del servicio.",
                            IsActive = true,
                            Name = "Comercializador del servicio"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StoreModules.StoreModule", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("ModuleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<float>("ModuleDiscountPrice")
                        .HasColumnType("real");

                    b.Property<float>("ModulePercentDiscountPrice")
                        .HasColumnType("real");

                    b.Property<float>("ModulePrice")
                        .HasColumnType("real");

                    b.Property<bool>("ModulePriceIncluded")
                        .HasColumnType("boolean");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.ToTable("StoreModule", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StorePaymentStatuses.StorePaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StorePaymentStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Created"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Notified"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Invoiced"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Approved"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Paid"
                        });
                });

            modelBuilder.Entity("Domain.Entities.StorePayments.StorePayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("NotificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("PaidDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PaymentBeforeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("StorePaymentStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("StorePaymentStatusId");

                    b.HasIndex("TenantId");

                    b.ToTable("StorePayment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StoreRoleFeatures.StoreRoleFeature", b =>
                {
                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StoreId", "RoleId", "FeatureId");

                    b.HasIndex("FeatureId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("StoreRoleFeature", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.StoreUsers.StoreUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "StoreId");

                    b.HasIndex("StoreId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StoreUser", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PaymentStartDate")
                        .HasColumnType("date");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Store", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SystemConfigurations.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SystemConfiguration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "TestingPeriodInMonths",
                            Value = "1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ReSellerPercentDiscountPrice",
                            Value = "25"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConnectionString")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenant", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8"),
                            ConnectionString = "",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 486, DateTimeKind.Unspecified).AddTicks(5502), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Default Tenant to create Default Store for Super Admin User",
                            IsActive = true,
                            Name = "Default Tenant"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserRoles.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserRole", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("38b96d85-bf75-41ca-bfd7-796e7fe0ebc8"),
                            RoleId = 1,
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsActive = true,
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8")
                        });
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CellPhone")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SelectedStoreId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("38b96d85-bf75-41ca-bfd7-796e7fe0ebc8"),
                            CellPhone = "52432968",
                            CreatedBy = new Guid("00000000-0000-0000-0000-000000000000"),
                            CreatedDate = new DateTimeOffset(new DateTime(2025, 4, 13, 18, 50, 15, 486, DateTimeKind.Unspecified).AddTicks(7709), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "lrscott83@gmail.com",
                            FullName = "Lizardo Romero",
                            IsActive = true,
                            Login = "admin",
                            Password = "XwHSL3RwmY9AkQLdRIeWr/H1xHm7ulj/la+EYwkLgrA=",
                            SelectedStoreId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TenantId = new Guid("b58bf718-c4ed-4ee9-a958-bb5a5db4f7e8")
                        });
                });

            modelBuilder.Entity("Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ProcessedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessage", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.HasOne("Domain.Entities.Modules.Module", "Module")
                        .WithMany("Features")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("Owner")
                        .HasForeignKey("Domain.Entities.Owners.Owner", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ReSellerOwners.ReSellerOwner", b =>
                {
                    b.HasOne("Domain.Entities.Owners.Owner", "Owner")
                        .WithOne("ReSellerOwner")
                        .HasForeignKey("Domain.Entities.ReSellerOwners.ReSellerOwner", "OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ReSellers.ReSeller", "ReSeller")
                        .WithMany("ReSellerOwners")
                        .HasForeignKey("ReSellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("ReSeller");
                });

            modelBuilder.Entity("Domain.Entities.ReSellers.ReSeller", b =>
                {
                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("ReSeller")
                        .HasForeignKey("Domain.Entities.ReSellers.ReSeller", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.StoreModules.StoreModule", b =>
                {
                    b.HasOne("Domain.Entities.Modules.Module", "Module")
                        .WithMany("StoreModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreModules")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.StorePayments.StorePayment", b =>
                {
                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StorePayments")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.StorePaymentStatuses.StorePaymentStatus", "StorePaymentStatus")
                        .WithMany("StorePayments")
                        .HasForeignKey("StorePaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("StorePaymentStatus");
                });

            modelBuilder.Entity("Domain.Entities.StoreRoleFeatures.StoreRoleFeature", b =>
                {
                    b.HasOne("Domain.Entities.Features.Feature", "Feature")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreRoleFeatures")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Feature");

                    b.Navigation("Role");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.StoreUsers.StoreUser", b =>
                {
                    b.HasOne("Domain.Entities.Stores.Store", "Store")
                        .WithMany("StoreUsers")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithOne("StoreUser")
                        .HasForeignKey("Domain.Entities.StoreUsers.StoreUser", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.HasOne("Domain.Entities.Owners.Owner", "Owner")
                        .WithMany("Stores")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Domain.Entities.UserRoles.UserRole", b =>
                {
                    b.HasOne("Domain.Entities.Roles.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Users.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Features.Feature", b =>
                {
                    b.Navigation("StoreRoleFeatures");
                });

            modelBuilder.Entity("Domain.Entities.Modules.Module", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("StoreModules");
                });

            modelBuilder.Entity("Domain.Entities.Owners.Owner", b =>
                {
                    b.Navigation("ReSellerOwner")
                        .IsRequired();

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("Domain.Entities.ReSellers.ReSeller", b =>
                {
                    b.Navigation("ReSellerOwners");
                });

            modelBuilder.Entity("Domain.Entities.Roles.Role", b =>
                {
                    b.Navigation("StoreRoleFeatures");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Domain.Entities.StorePaymentStatuses.StorePaymentStatus", b =>
                {
                    b.Navigation("StorePayments");
                });

            modelBuilder.Entity("Domain.Entities.Stores.Store", b =>
                {
                    b.Navigation("StoreModules");

                    b.Navigation("StorePayments");

                    b.Navigation("StoreRoleFeatures");

                    b.Navigation("StoreUsers");
                });

            modelBuilder.Entity("Domain.Entities.Users.User", b =>
                {
                    b.Navigation("Owner");

                    b.Navigation("ReSeller");

                    b.Navigation("StoreUser");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
