import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { unwrapDekWithDek, DEK_WRAP_ITERATIONS } from '../dek-unwrap';
import { pbkdf2Base64 } from '../offline-crypto';
import { aesGcmDecrypt } from '../../storage/aes-gcm';
import { bytesFromBase64 } from '../../storage/base64';

// seamless-store-switch v2 — cross-stack KAT for `unwrapDekWithDek`, the
// client side of `PUT /v1/stores/switch`'s SwitchMyStoreResult. The vector is
// generated by `backend/scripts/generate-switch-dek-kat.ps1` with the REAL
// backend algorithm (HKDF GetDek + StoreKeyWrapService.WrapDek) — the same
// discipline as `dek-unwrap.kat.test.ts`. Reads via readFileSync, NOT a static
// import — Vitest's Vite root is `apps/web-store-pos` and a static import 8
// levels above it risks fs.strict denial.
const katPath = resolve(
  dirname(fileURLToPath(import.meta.url)),
  '../'.repeat(8),
  'docs/contracts/switch-store-dek-kat.json',
);
const kat = JSON.parse(readFileSync(katPath, 'utf-8')) as {
  masterSecret: string;
  storeA: string;
  storeB: string;
  currentDek: string;
  targetDek: string;
  wrappedDek: string;
  wrapSalt: string;
  wrapIv: string;
};

describe('unwrapDekWithDek — known-answer vector (dotnet-backend, cross-stack)', () => {
  it('vector carries the two store ids and 32-byte keys', () => {
    expect(kat.storeA).toBe('a1a1a1a1-a1a1-a1a1-a1a1-a1a1a1a1a1a1');
    expect(kat.storeB).toBe('b2b2b2b2-b2b2-b2b2-b2b2-b2b2b2b2b2b2');
    expect(bytesFromBase64(kat.currentDek).length).toBe(32);
    expect(bytesFromBase64(kat.targetDek).length).toBe(32);
  });

  it('unwraps the backend wrap with the CURRENT DEK to the exact TARGET DEK bytes', async () => {
    const recovered = await unwrapDekWithDek(bytesFromBase64(kat.currentDek), {
      wrappedDek: kat.wrappedDek,
      wrapSalt: kat.wrapSalt,
      wrapIv: kat.wrapIv,
    });

    const expected = bytesFromBase64(kat.targetDek);
    expect(Array.from(recovered)).toEqual(Array.from(expected));
    expect(recovered.length).toBe(32);
  });

  it('rejects with DekUnwrapError when the KEK material is wrong', async () => {
    const wrongDek = bytesFromBase64(kat.targetDek); // swapped: KEK must be the CURRENT dek
    await expect(
      unwrapDekWithDek(wrongDek, {
        wrappedDek: kat.wrappedDek,
        wrapSalt: kat.wrapSalt,
        wrapIv: kat.wrapIv,
      }),
    ).rejects.toThrow('Failed to unwrap the data encryption key');
  });

  it('pbkdf2Base64 with the same inputs reproduces the vector KEK derivation path (DEK_WRAP_ITERATIONS pin)', async () => {
    // The backend hardcodes 210_000 iterations; the client's constant must
    // never drift or every switch wrap would fail to open.
    expect(DEK_WRAP_ITERATIONS).toBe(210_000);
    // Sanity: deriving with the CURRENT dek's base64 text + the vector salt
    // must produce a KEK that decrypts the vector ciphertext (via
    // aesGcmDecrypt), proving the exact KEK material — base64 TEXT of the
    // DEK, UTF-8 encoded — matches the backend's WrapDek input.
    const kekBase64 = await pbkdf2Base64(kat.currentDek, kat.wrapSalt, DEK_WRAP_ITERATIONS);
    const wrapped = bytesFromBase64(kat.wrappedDek);
    const plaintext = aesGcmDecrypt(
      bytesFromBase64(kekBase64),
      bytesFromBase64(kat.wrapIv),
      wrapped,
    );
    expect(Array.from(plaintext)).toEqual(Array.from(bytesFromBase64(kat.targetDek)));
  });
});
