//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal I18n() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tsc.Resources.Localization.I18n", typeof(I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Check not found.
        /// </summary>
        internal static string BackgroundCheckNotFound {
            get {
                return ResourceManager.GetString("BackgroundCheckNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseFee.
        /// </summary>
        internal static string BaseFee {
            get {
                return ResourceManager.GetString("BaseFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Address is main address.
        /// </summary>
        internal static string CarrierAddressIsMain {
            get {
                return ResourceManager.GetString("CarrierAddressIsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Address not found.
        /// </summary>
        internal static string CarrierAddressNotFound {
            get {
                return ResourceManager.GetString("CarrierAddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier already exists.
        /// </summary>
        internal static string CarrierAlreadyExists {
            get {
                return ResourceManager.GetString("CarrierAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier has assigned insurance criterion.
        /// </summary>
        internal static string CarrierHasAssignedInsuranceCriterion {
            get {
                return ResourceManager.GetString("CarrierHasAssignedInsuranceCriterion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier has assigned payment method.
        /// </summary>
        internal static string CarrierHasAssignedPaymentMethod {
            get {
                return ResourceManager.GetString("CarrierHasAssignedPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Ifta not found.
        /// </summary>
        internal static string CarrierIftaNotFound {
            get {
                return ResourceManager.GetString("CarrierIftaNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Not Created.
        /// </summary>
        internal static string CarrierNotCreated {
            get {
                return ResourceManager.GetString("CarrierNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier not found.
        /// </summary>
        internal static string CarrierNotFound {
            get {
                return ResourceManager.GetString("CarrierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier payment method not found.
        /// </summary>
        internal static string CarrierPaymentMethodNotFound {
            get {
                return ResourceManager.GetString("CarrierPaymentMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier PSP inspection level not found.
        /// </summary>
        internal static string CarrierPspInspectionLevelNotFound {
            get {
                return ResourceManager.GetString("CarrierPspInspectionLevelNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier Requirement value is invalid.
        /// </summary>
        internal static string CarrierRequirementValueInvalid {
            get {
                return ResourceManager.GetString("CarrierRequirementValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carrier service not found.
        /// </summary>
        internal static string CarrierServiceNotFound {
            get {
                return ResourceManager.GetString("CarrierServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City not found.
        /// </summary>
        internal static string CityNotFound {
            get {
                return ResourceManager.GetString("CityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearinghouse not found.
        /// </summary>
        internal static string ClearinghouseNotFound {
            get {
                return ResourceManager.GetString("ClearinghouseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client not found.
        /// </summary>
        internal static string ClientNotFound {
            get {
                return ResourceManager.GetString("ClientNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company could not be created.
        /// </summary>
        internal static string CompanyNotCreated {
            get {
                return ResourceManager.GetString("CompanyNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found.
        /// </summary>
        internal static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company could not be updated.
        /// </summary>
        internal static string CompanyNotUpdated {
            get {
                return ResourceManager.GetString("CompanyNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Invalid.
        /// </summary>
        internal static string DateInvalid {
            get {
                return ResourceManager.GetString("DateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission.
        /// </summary>
        internal static string DontHavePermission {
            get {
                return ResourceManager.GetString("DontHavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverApplicationAdditionalDocument not found.
        /// </summary>
        internal static string DriverApplicationAdditionalDocumentNotFound {
            get {
                return ResourceManager.GetString("DriverApplicationAdditionalDocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Application Hiring Service not found.
        /// </summary>
        internal static string DriverApplicationHiringServiceNotFound {
            get {
                return ResourceManager.GetString("DriverApplicationHiringServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exists a Driver Application in progess.
        /// </summary>
        internal static string DriverApplicationInProgress {
            get {
                return ResourceManager.GetString("DriverApplicationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Application not found.
        /// </summary>
        internal static string DriverApplicationNotFound {
            get {
                return ResourceManager.GetString("DriverApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverApplicationOrder not found.
        /// </summary>
        internal static string DriverApplicationOrderNotFound {
            get {
                return ResourceManager.GetString("DriverApplicationOrderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverApplicationPersonalInformationNotFound.
        /// </summary>
        internal static string DriverApplicationPersonalInformationNotFound {
            get {
                return ResourceManager.GetString("DriverApplicationPersonalInformationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver.
        /// </summary>
        internal static string DriverAudienceTypeName {
            get {
                return ResourceManager.GetString("DriverAudienceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver License already exists.
        /// </summary>
        internal static string DriverLicenseAlreadyExists {
            get {
                return ResourceManager.GetString("DriverLicenseAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverLicenseDesignation not found.
        /// </summary>
        internal static string DriverLicenseDesignationNotFound {
            get {
                return ResourceManager.GetString("DriverLicenseDesignationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverLicenseEndorsement not found.
        /// </summary>
        internal static string DriverLicenseEndorsementNotFound {
            get {
                return ResourceManager.GetString("DriverLicenseEndorsementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverLicenseRestriction not found.
        /// </summary>
        internal static string DriverLicenseRestrictionNotFound {
            get {
                return ResourceManager.GetString("DriverLicenseRestrictionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driver Payment Frequency is not unique.
        /// </summary>
        internal static string DriverPaymentFrequencyIsNotUnique {
            get {
                return ResourceManager.GetString("DriverPaymentFrequencyIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverPaymentFrequency payment frequency not found.
        /// </summary>
        internal static string DriverPaymentFrequencyPaymentFrequencyNotFound {
            get {
                return ResourceManager.GetString("DriverPaymentFrequencyPaymentFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DrivingHistoryType not found.
        /// </summary>
        internal static string DrivingHistoryTypeNotFound {
            get {
                return ResourceManager.GetString("DrivingHistoryTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Test not found.
        /// </summary>
        internal static string DrugTestNotFound {
            get {
                return ResourceManager.GetString("DrugTestNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Test type not found.
        /// </summary>
        internal static string DrugTestTypeNotFound {
            get {
                return ResourceManager.GetString("DrugTestTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date is invalid.
        /// </summary>
        internal static string EffectiveDateInvalid {
            get {
                return ResourceManager.GetString("EffectiveDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error creating user &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorCreatingUser {
            get {
                return ResourceManager.GetString("ErrorCreatingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating role &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUpdatingRole {
            get {
                return ResourceManager.GetString("ErrorUpdatingRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating roles for user &apos;{0}&apos;.
        /// </summary>
        internal static string ErrorUpdatingUserRoles {
            get {
                return ResourceManager.GetString("ErrorUpdatingUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EscrowAccount type not found.
        /// </summary>
        internal static string EscrowAccountTypeNotFound {
            get {
                return ResourceManager.GetString("EscrowAccountTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EscrowFrequency not found.
        /// </summary>
        internal static string EscrowFrequencyNotFound {
            get {
                return ResourceManager.GetString("EscrowFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; has role {1} in company {2}.
        /// </summary>
        internal static string ExistUserRole {
            get {
                return ResourceManager.GetString("ExistUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExpirationDate.
        /// </summary>
        internal static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Payment Rate is not unique.
        /// </summary>
        internal static string ExtraPaymentRateIsNotUnique {
            get {
                return ResourceManager.GetString("ExtraPaymentRateIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraPaymentRate reason not found.
        /// </summary>
        internal static string ExtraPaymentRateReasonNotFound {
            get {
                return ResourceManager.GetString("ExtraPaymentRateReasonNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraPaymentRate trailer type not found.
        /// </summary>
        internal static string ExtraPaymentRateTrailerTypeNotFound {
            get {
                return ResourceManager.GetString("ExtraPaymentRateTrailerTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FixedRate frequency not found.
        /// </summary>
        internal static string FixedRateFrequencyNotFound {
            get {
                return ResourceManager.GetString("FixedRateFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment is not unique.
        /// </summary>
        internal static string FixedRateIsNotUnique {
            get {
                return ResourceManager.GetString("FixedRateIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective Carrier Requirement not found.
        /// </summary>
        internal static string FutureEffectiveCarrierRequirementNotFound {
            get {
                return ResourceManager.GetString("FutureEffectiveCarrierRequirementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective DriverPaymentFrequency not found.
        /// </summary>
        internal static string FutureEffectiveDriverPaymentFrequencyNotFound {
            get {
                return ResourceManager.GetString("FutureEffectiveDriverPaymentFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective EscrowAccount not found.
        /// </summary>
        internal static string FutureEffectiveEscrowAccountNotFound {
            get {
                return ResourceManager.GetString("FutureEffectiveEscrowAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective ExtraPaymentRate not found.
        /// </summary>
        internal static string FutureEffectiveExtraPaymentRateNotFound {
            get {
                return ResourceManager.GetString("FutureEffectiveExtraPaymentRateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective Fixed Rate not found.
        /// </summary>
        internal static string FutureEffectiveFixedRateNotFound {
            get {
                return ResourceManager.GetString("FutureEffectiveFixedRateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective Percentage Fee Package not found.
        /// </summary>
        internal static string FutureEffectivePercentageFeePackageNotFound {
            get {
                return ResourceManager.GetString("FutureEffectivePercentageFeePackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future effective Rate per miles not found.
        /// </summary>
        internal static string FutureEffectivePerMilesRateNotFound {
            get {
                return ResourceManager.GetString("FutureEffectivePerMilesRateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GlobalAdmin request without TenantId.
        /// </summary>
        internal static string GlobalAdminRequestWithoutTenantId {
            get {
                return ResourceManager.GetString("GlobalAdminRequestWithoutTenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than or equals to {1}.
        /// </summary>
        internal static string GreaterThanOrEqualsTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater than {1}.
        /// </summary>
        internal static string GreaterThanTo {
            get {
                return ResourceManager.GetString("GreaterThanTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HasDriverLicense With Invalid Answer.
        /// </summary>
        internal static string HasDriverLicenseWithValidAnswer {
            get {
                return ResourceManager.GetString("HasDriverLicenseWithValidAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hiring checklist could not be created.
        /// </summary>
        internal static string HiringChecklistNotCreated {
            get {
                return ResourceManager.GetString("HiringChecklistNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hiring process could not be created.
        /// </summary>
        internal static string HiringProcessNotCreated {
            get {
                return ResourceManager.GetString("HiringProcessNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring process not found.
        /// </summary>
        internal static string HiringProcessNotFound {
            get {
                return ResourceManager.GetString("HiringProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hiring process could not be updated.
        /// </summary>
        internal static string HiringProcessNotUpdated {
            get {
                return ResourceManager.GetString("HiringProcessNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hiring service not found.
        /// </summary>
        internal static string HiringServiceNotFound {
            get {
                return ResourceManager.GetString("HiringServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This carrier has an inivalid option with the insurance criterion.
        /// </summary>
        internal static string InsuranceCriterionInvalid {
            get {
                return ResourceManager.GetString("InsuranceCriterionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurange criterion not found.
        /// </summary>
        internal static string InsuranceCriterionNotFound {
            get {
                return ResourceManager.GetString("InsuranceCriterionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance criterion not found.
        /// </summary>
        internal static string InsuranceCriterionTypeNotFound {
            get {
                return ResourceManager.GetString("InsuranceCriterionTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The insurance criterion values are invalid..
        /// </summary>
        internal static string InsuranceCriterionValuesInvalid {
            get {
                return ResourceManager.GetString("InsuranceCriterionValuesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance exception value is invalid.
        /// </summary>
        internal static string InsuranceExceptionInvalid {
            get {
                return ResourceManager.GetString("InsuranceExceptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance exception noy found.
        /// </summary>
        internal static string InsuranceExceptionNotFound {
            get {
                return ResourceManager.GetString("InsuranceExceptionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance not found.
        /// </summary>
        internal static string InsuranceNotFound {
            get {
                return ResourceManager.GetString("InsuranceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance type not found.
        /// </summary>
        internal static string InsuranceTypeNotFound {
            get {
                return ResourceManager.GetString("InsuranceTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance with this type already exists.
        /// </summary>
        internal static string InsuranceWithTypeExists {
            get {
                return ResourceManager.GetString("InsuranceWithTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be in mail format.
        /// </summary>
        internal static string IsEmailFormatInvalid {
            get {
                return ResourceManager.GetString("IsEmailFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required.
        /// </summary>
        internal static string IsRequired {
            get {
                return ResourceManager.GetString("IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be lest or equals to {1}.
        /// </summary>
        internal static string LessOrEqualsTo {
            get {
                return ResourceManager.GetString("LessOrEqualsTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be greater or equals to 0..
        /// </summary>
        internal static string LessThanZero {
            get {
                return ResourceManager.GetString("LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string MeasureHeaderAge {
            get {
                return ResourceManager.GetString("MeasureHeaderAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        internal static string MeasureHeaderMonths {
            get {
                return ResourceManager.GetString("MeasureHeaderMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string MeasureHeaderPoints {
            get {
                return ResourceManager.GetString("MeasureHeaderPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string MeasureHeaderYear {
            get {
                return ResourceManager.GetString("MeasureHeaderYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        internal static string MeasureHeaderYears {
            get {
                return ResourceManager.GetString("MeasureHeaderYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years old.
        /// </summary>
        internal static string MeasureValueAge {
            get {
                return ResourceManager.GetString("MeasureValueAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} months.
        /// </summary>
        internal static string MeasureValueMonths {
            get {
                return ResourceManager.GetString("MeasureValueMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} points.
        /// </summary>
        internal static string MeasureValuePoints {
            get {
                return ResourceManager.GetString("MeasureValuePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year {0}.
        /// </summary>
        internal static string MeasureValueYear {
            get {
                return ResourceManager.GetString("MeasureValueYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} years.
        /// </summary>
        internal static string MeasureValueYears {
            get {
                return ResourceManager.GetString("MeasureValueYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module not found.
        /// </summary>
        internal static string ModuleNotFound {
            get {
                return ResourceManager.GetString("ModuleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Motor Vehicle Record not found.
        /// </summary>
        internal static string MotorVehicleRecordNotFound {
            get {
                return ResourceManager.GetString("MotorVehicleRecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must {1} characters.
        /// </summary>
        internal static string MustLengthCharacters {
            get {
                return ResourceManager.GetString("MustLengthCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must numeric.
        /// </summary>
        internal static string MustNumeric {
            get {
                return ResourceManager.GetString("MustNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Has Any Service PendingPayment.
        /// </summary>
        internal static string NoHasAnyServicePendingPayment {
            get {
                return ResourceManager.GetString("NoHasAnyServicePendingPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not authorized.
        /// </summary>
        internal static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Date is invalid.
        /// </summary>
        internal static string NotificationDateInvalid {
            get {
                return ResourceManager.GetString("NotificationDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotificationTemplate not found.
        /// </summary>
        internal static string NotificationTemplateNotFound {
            get {
                return ResourceManager.GetString("NotificationTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit exceded for this operation.
        /// </summary>
        internal static string OperationLimitExceded {
            get {
                return ResourceManager.GetString("OperationLimitExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original CDL Issue Date is invalid.
        /// </summary>
        internal static string OriginalCDLIssueDateInvalid {
            get {
                return ResourceManager.GetString("OriginalCDLIssueDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pay {0} fee per transaction..
        /// </summary>
        internal static string PaymentMethodFeeValueText {
            get {
                return ResourceManager.GetString("PaymentMethodFeeValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment method could not be created.
        /// </summary>
        internal static string PaymentMethodNotCreated {
            get {
                return ResourceManager.GetString("PaymentMethodNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment method not found.
        /// </summary>
        internal static string PaymentMethodNotFound {
            get {
                return ResourceManager.GetString("PaymentMethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment method could not be updated.
        /// </summary>
        internal static string PaymentMethodNotUpdated {
            get {
                return ResourceManager.GetString("PaymentMethodNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pay {0} percent per transaction..
        /// </summary>
        internal static string PaymentMethodPercentValueText {
            get {
                return ResourceManager.GetString("PaymentMethodPercentValueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Percentage Fee frequency not found.
        /// </summary>
        internal static string PercentageFeePackageFrequencyNotFound {
            get {
                return ResourceManager.GetString("PercentageFeePackageFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per miles is not unique.
        /// </summary>
        internal static string PerMilesRateIsNotUnique {
            get {
                return ResourceManager.GetString("PerMilesRateIsNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate per miles trailer type not found.
        /// </summary>
        internal static string PerMilesRateTrailerTypeNotFound {
            get {
                return ResourceManager.GetString("PerMilesRateTrailerTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PSP not found.
        /// </summary>
        internal static string PspNotFound {
            get {
                return ResourceManager.GetString("PspNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record result not found.
        /// </summary>
        internal static string RecordResultNotFound {
            get {
                return ResourceManager.GetString("RecordResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road test result not found.
        /// </summary>
        internal static string RoadTestResultNotFound {
            get {
                return ResourceManager.GetString("RoadTestResultNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role already exists.
        /// </summary>
        internal static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found.
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaleFee.
        /// </summary>
        internal static string SaleFee {
            get {
                return ResourceManager.GetString("SaleFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers count is invalid.
        /// </summary>
        internal static string SecurityAnswerCountInvalid {
            get {
                return ResourceManager.GetString("SecurityAnswerCountInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service frequency not found.
        /// </summary>
        internal static string ServiceFrequencyNotFound {
            get {
                return ResourceManager.GetString("ServiceFrequencyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not found.
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureProvider is invalid.
        /// </summary>
        internal static string SignatureProviderInvalid {
            get {
                return ResourceManager.GetString("SignatureProviderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureTemplateFieldIdentifier not ends with suffix or is not required or is not readonly.
        /// </summary>
        internal static string SignatureTemplateFieldIInvalid {
            get {
                return ResourceManager.GetString("SignatureTemplateFieldIInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature Template not found.
        /// </summary>
        internal static string SignatureTemplateNotFound {
            get {
                return ResourceManager.GetString("SignatureTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State not found.
        /// </summary>
        internal static string StateNotFound {
            get {
                return ResourceManager.GetString("StateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedErrorUploadingFile.
        /// </summary>
        internal static string UnexpectedErrorUploadingFile {
            get {
                return ResourceManager.GetString("UnexpectedErrorUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &apos;{0}&apos; does not have a password set for local login.
        /// </summary>
        internal static string User_does_not_have_a_password_set_for_local_login {
            get {
                return ResourceManager.GetString("User does not have a password set for local login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UserAudienceTypeName {
            get {
                return ResourceManager.GetString("UserAudienceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user could not be created.
        /// </summary>
        internal static string UserNotCreated {
            get {
                return ResourceManager.GetString("UserNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        internal static string UserNotFoud {
            get {
                return ResourceManager.GetString("UserNotFoud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not have the role &apos;{0}&apos; configured.
        /// </summary>
        internal static string UserNotRole {
            get {
                return ResourceManager.GetString("UserNotRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekday is required.
        /// </summary>
        internal static string WeekdayRequired {
            get {
                return ResourceManager.GetString("WeekdayRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not logged in with an external user.
        /// </summary>
        internal static string You_are_not_logged_in_with_an_external_user {
            get {
                return ResourceManager.GetString("You are not logged in with an external user", resourceCulture);
            }
        }
    }
}
